services:
  frontend:
    build: ./frontend
    container_name: nginx-frontend
    ports:
      - "8443:443"
    depends_on:
      - backend
    volumes:
      - media:/media/
      # - ./frontend/static-html:/usr/share/nginx/html
      # - ./frontend/nginx.conf:/etc/nginx/nginx.conf

  backend:
    build: ./backend/
    container_name: django-backend
    env_file: .env
    volumes:
      - media:/media/
    depends_on:
      db:
        condition: service_healthy

  db:
    image: postgres:alpine
    container_name: psql-database
    env_file: .env
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: pg_isready -U postgres
      interval: 1s
      timeout: 5s
      retries: 10

  redis:
    image: redis:alpine
    container_name: redis-backend

volumes:
  postgres_data:
  grafana_data:
  media:
