services:
  frontend:
    build: ./frontend
    ports:
      - "8080:80"
    volumes:
      - ${APP_DIR}/uploads:/usr/share/nginx/html/uploads
    depends_on:
      - backend

  backend:
    build: ./backend
    ports:
      - "4567:4567"
    volumes:
      - ${APP_DIR}/uploads:/app/uploads
    depends_on:
      - db
    environment:
      DATABASE_URL: postgres://user:password@db/pong
      SESSION_SECRET: your_session_secret_here

  db:
    image: postgres:13
    volumes:
      - ${APP_DIR}/db/init.sql:/docker-entrypoint-initdb.d/init.sql
      - pgdata:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: pong

volumes:
  pgdata:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: ${APP_DIR}/db/pgdata