services:
  frontend:
    build: ./frontend
    ports:
      - "8080:80"
    volumes:
      - ${APP_DIR}/uploads:/usr/share/nginx/html/uploads
    depends_on:
      - backend

  backend:
    build: ./backend/
    container_name: django-backend
    env_file: .env
    volumes:
      - ./:/code/
    ports:
      - 8000:8000
    depends_on:
      db:
        condition: service_healthy

  db:
    image: postgres:alpine
    container_name: psql-database
    ports:
      - 5432:5432
    environment:
      - POSTGRES_DB=transcendence
    env_file: .env
    healthcheck:
      test: pg_isready -U postgres
      interval: 1s
      timeout: 5s
      retries: 10
