# Generated by Django 5.1 on 2024-09-11 16:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserFriend',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('rq1', 'UID_1 is making a friend request to UID_2'), ('rq2', 'UID_2 is making a friend request to UID_1'), ('fri', 'UID_1 and UID_2 are friends')], max_length=3)),
                ('uid1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='uid1', to=settings.AUTH_USER_MODEL)),
                ('uid2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='uid2', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'constraints': [models.CheckConstraint(condition=models.Q(('uid1__lt', models.F('uid2'))), name='uid1_less_than_uid2')],
            },
        ),
    ]
