# Generated by Django 5.1 on 2024-09-13 20:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('p1_score', models.PositiveSmallIntegerField()),
                ('p2_score', models.PositiveSmallIntegerField()),
                ('time_start', models.DateTimeField()),
                ('time_end', models.DateTimeField()),
                ('p1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='p1', to='user.user')),
                ('p2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='p2', to='user.user')),
            ],
        ),
    ]
