CREATE TABLE users (
	id SERIAL PRIMARY KEY,
	username VARCHAR(50) UNIQUE NOT NULL,
	password_hash VARCHAR(255) NOT NULL,
	email VARCHAR(255) UNIQUE NOT NULL,
	first_name VARCHAR(50),
	age INTEGER,
	created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE games (
	id SERIAL PRIMARY KEY,
	player1_id INTEGER REFERENCES users(id),
	player2_id INTEGER REFERENCES users(id),
	player1_score INTEGER DEFAULT 0,
	player2_score INTEGER DEFAULT 0,
	started_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
	ended_at TIMESTAMP
);

CREATE TABLE messages (
	id SERIAL PRIMARY KEY,
	sender_id INTEGER REFERENCES users(id),
	content TEXT NOT NULL,
	sent_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);